name: Deploy to Cloud Run - Staging 
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Branch, tag or commit to deploy'
        default: dev
        required: true

env:
  PROJECT_ID: "${{ secrets.GCLOUD_PROJECT_ID_STAGING }}"
  REGION: ${{ vars.GCLOUD_REGION || 'europe-west1'}}
  SERVICE: iot-simulator-staging
  FUNCTION_NAME: iot-simulator
  SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_STAGING }}
  GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_STAGING }}

  SERVICE_SENSOR_DATA_DISPATCHER_URL: ${{vars.SERVICE_SENSOR_DATA_DISPATCHER_URL_STAGING}}
 
  GCP_LOGGER_NAME: ${{ vars.GCP_LOGGER_NAME_STAGING || 'tenco-cloud-event-sensor-dispatcher-staging' }}

  MEMORY: ${{ vars.MEMORY_STAGING || '1024Mi' }}
  CPU: ${{ vars.CPU_STAGING || '1' }}
  MAX_INSTANCES: ${{ vars.MAX_INSTANCES_STAGING || '1' }}
  MIN_INSTANCES: ${{ vars.MIN_INSTANCES_STAGING || '0' }}
  PORT: ${{ vars.PORT_STAGING || '8080' }}
  CONCURRENCY: ${{ vars.CONCURRENCY_STAGING || '30' }}
  TIMEOUT: ${{ vars.TIMEOUT_STAGING || '180' }}


jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🕵️
        uses: actions/checkout@v4
      
      - name: Use Node.js 🦄
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      
      - name: Install Dependencies 🔧
        run: |
          npm install --immutable

      - name: Build Project 🏗️
        run: |
          npm run build

      - name: Verify Required Variables ✅
        run: |
          required_vars=("PROJECT_ID" "SERVICE_ACCOUNT" "GCLOUD_SERVICE_KEY")
          for var in "${required_vars[@]}"; do
            if [ -z "${!var}" ]; then
              echo "Error: $var is not set."
              exit 1
            fi
          done

      - name: Google Auth 🔒
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCLOUD_SERVICE_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Prepare for Deployment 🛠️
        run: |
          # Créer un package.json spécifique pour le déploiement dans dist
          cat > dist/package.json << EOF
          {
            "name": "cloud-function-iot-simulator",
            "version": "1.0.0",
            "main": "index.js",
            "dependencies": $(node -e "console.log(JSON.stringify(require('./package.json').dependencies))")
          }
          EOF

      - name: Deploy to Cloud Function 🚀
        id: deploy
        run: |
          ENV_VARS="NODE_ENV=stage,GCP_LOGGER_NAME=$GCP_LOGGER_NAME,GCLOUD_REGION=$GCLOUD_REGION,GCP_PROJECT_ID=$PROJECT_ID,SERVICE_SENSOR_DATA_DISPATCHER_URL=$SERVICE_SENSOR_DATA_DISPATCHER_URL,SERVICE_ACCOUNT=$SERVICE_ACCOUNT"
        
          gcloud functions deploy iot-simulator \
            --project=$PROJECT_ID \
            --region=$REGION \
            --runtime=nodejs20 \
            --source=dist \
            --entry-point=iot-simulator \
            --memory=$MEMORY \
            --service-account=$SERVICE_ACCOUNT \
            --set-env-vars=$ENV_VARS
            
      # If required, use the Cloud Run url output in later steps
      - name: Show Deployment Info 👀
        run: |
          gcloud functions describe iot-simulator --region=$REGION